AWSTemplateFormatVersion: 2010-09-09
Parameters:
  BucketName:
    Description: The name of the S3 bucket
    Type: String
    AllowedPattern: '^[a-zA-Z0-9.-_]{3,63}$'
    ConstraintDescription: Bucket name can contain only letters, numbers, periods, hyphens.
  IndexDocumentName:
    Description: The name of the index document for S3 Static Website
    Type: String
  ErrorDocumentName:
    Description: The name of the error document for S3 Static Website
    Type: String
  BucketIdName:
    Description: The name of the bucket policy Id for S3 Static Website
    Type: String

Resources:
  sitewbucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref BucketName
      PublicAccessBlockConfiguration:
        BlockPublicAcls: false
        BlockPublicPolicy: false
        IgnorePublicAcls: false
        RestrictPublicBuckets: false
      WebsiteConfiguration:
        IndexDocument: !Ref IndexDocumentName
        ErrorDocument: !Ref ErrorDocumentName
    DeletionPolicy: Retain
    UpdateReplacePolicy: Retain
  BucketPolicy:
    Type: 'AWS::S3::BucketPolicy'
    Properties:
      PolicyDocument:
        Id: !Ref BucketIdName
        Version: 2012-10-17
        Statement:
          - Sid: PublicReadForGetBucketObjects
            Effect: Allow
            Principal: '*'
            Action: 's3:GetObject'
            Resource: !Join 
              - ''
              - - 'arn:aws:s3:::'
                - !Ref BucketName
                - /*
      Bucket: !Ref BucketName

Outputs:
  BucketNameOutput:
    Description: The name of the S3 bucket
    Value: !Ref sitewbucket
    Export:
      Name: !Sub "${AWS::StackName}-BucketName"
  WebsiteEndpoint:
    Description: The website endpoint of the S3 bucket
    Value: !GetAtt sitewbucket.WebsiteURL
    Export:
      Name: !Sub "${AWS::StackName}-WebsiteEndpoint" 