AWSTemplateFormatVersion: 2010-09-09
Resources:
  sitewbucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: sitewbucket
      PublicAccessBlockConfiguration:
        BlockPublicAcls: false
        BlockPublicPolicy: false
        IgnorePublicAcls: false
        RestrictPublicBuckets: false
      WebsiteConfiguration:
        IndexDocument: index.html
        ErrorDocument: error.html
    DeletionPolicy: Retain
    UpdateReplacePolicy: Retain
  BucketPolicy:
    Type: 'AWS::S3::BucketPolicy'
    Properties:
      PolicyDocument:
        Id: MyPolicy
        Version: 2012-10-17
        Statement:
          - Sid: PublicReadForGetBucketObjects
            Effect: Allow
            Principal: '*'
            Action: 's3:GetObject'
            Resource: !Join 
              - ''
              - - 'arn:aws:s3:::'
                - !Ref sitewbucket
                - /*
      Bucket: !Ref sitewbucket
      
  SiteSG:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allow access on ports 80 and 22
      GroupName: Website SG
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 
      Tags:
        - Key: Name
          Value: Website SG
      VpcId: 

  SiteInstance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t2.micro
      SubnetId: subnet-d3f6dadd
      SecurityGroupIds:
        - !Ref SiteSG
      KeyName: SitePair
      ImageId: ami-0c8e23f950c7725b9 
      Tags:
        - Key: Name
          Value: MySiteServer
      UserData:
        Fn::Base64:
          !Sub |
            #!/bin/bash -xe
            sudo su
            yum update -y
            yum install -y httpd
            systemctl enable httpd 
            systemctl start httpd
            echo "<h1>Hello World from $(hostname -f)</h1>" > /var/www/html/index.html
            